version: 1
disable_existing_loggers: true

formatters:
  simple:
    (): shm.logging.HighlightingFormatter
    style: '{'
    format: '[{asctime}] [{process}] [{threadName}] {log_color}[{levelname}]{reset} {name} - {message}'
    datefmt: '%Y-%m-%d %H:%M:%S.%f%z'
    reset: false

  access:
    (): uvicorn.logging.AccessFormatter
    style: '{'
    fmt: '{client_addr} - "{request_line}" {status_code}'

handlers:
  noop:
    class: logging.NullHandler

  console:
    class: logging.StreamHandler
    formatter: simple

  access:
    class: logging.StreamHandler
    formatter: access

# Configure the root logger
root:
  level: WARNING
  handlers:
    - console

loggers:
  shm:
    level: INFO

  uvicorn:
    level: INFO

  uvicorn.access:
    # set level to INFO to enable access logs
    level: WARNING
    propagate: false
    handlers:
      - access

  pyecobee.utilities:
    level: FATAL
