[project]
name = "shm"
version = "0.0.0"
description = "Smart Home Prometheus Metrics"
authors = [
    { name = "Clark Perkins", email = "clarkperkins@users.noreply.github.com" }
]
requires-python = ">=3.12.0,<4.0"
dependencies = [
    "anyio",
    "colorlog",
    "fastapi",
    "kubernetes_asyncio",
    "prometheus-client",
    "prometheus-fastapi-instrumentator",
    "pydantic",
    "pydantic-settings",
    "pyecobee",
    "pysmartthings",
    "pyyaml",
    "uvicorn",
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
black = "*"
isort = "*"
mypy = "*"
pylint = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-cov = "*"
pytest-mock = "*"
types-pyyaml = "*"


[tool.coverage.run]
branch = true
relative_files = true

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_lines = [
    # Have to re-enable the standard pragma
    "pragma: no cover",
    # Don't complain about missing debug-only code:
    "def __repr__",
    "if self.debug",
    # Don't complain if tests don't hit defensive assertion code:
    "raise AssertionError",
    "raise NotImplementedError",
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
]

ignore_errors = true

[tool.coverage.html]
directory = "reports/coverage/html"
title = "shm coverage"

[tool.coverage.xml]
output = "reports/coverage/coverage.xml"


[tool.isort]
profile = "black"
skip_gitignore = true

[tool.mypy]
check_untyped_defs = true
plugins = [
    "pydantic.mypy",
]

[[tool.mypy.overrides]]
module = [
    "kubernetes_asyncio.*",
    "pyecobee",
    "pysmartthings",
    "uvicorn",
]
ignore_missing_imports = true
