apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "smart-home-metrics.fullname" . }}
  labels:
    {{- include "smart-home-metrics.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "create", "update", "patch"]
