apiVersion: v1
kind: Service
metadata:
  name: {{ include "smart-home-metrics.fullname" . }}
  labels:
    {{- include "smart-home-metrics.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 9000
      targetPort: http-metrics
      protocol: TCP
      name: http-metrics
  selector:
    {{- include "smart-home-metrics.selectorLabels" . | nindent 4 }}
