name: Build & Deploy

on:
  push:
    tags: [ '*' ]
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade poetry

      - name: Install Dependencies
        run: |
          poetry install

      - name: Run Checks
        run: |
          make check

#      - name: Run Tests
#        run: |
#          make test
#
#      - name: Publish Test Results
#        uses: EnricoMi/publish-unit-test-result-action@v1
#        if: always()
#        with:
#          files: reports/tests/*.xml

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v1.6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy:
    name: Deploy

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Docker Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: clarkperkins
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u clarkperkins --password-stdin https://ghcr.io

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/clarkperkins/stpm
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr
          flavor: |
            latest=${{ github.ref_name == github.event.repository.default_branch }}

      - name: Docker Build and Push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Helm Chart Version
        id: helm-version
        run: |
          if [[ "${{ github.event_name }}" == "push" && "${{ github.ref_type }}" == "tag" ]]; then
            echo "::set-output name=version::${{ steps.meta.outputs.version }}"
          else
            echo "::set-output name=version::$(date +'%Y.%-m.%-d')-${{ steps.meta.outputs.version }}.$(date +'%-H.%-M.%-S')"
          fi

      - name: Helm Build
        run: |
          helm package charts/stpm -u -d charts --version ${{ steps.helm-version.outputs.version }} --app-version ${{ steps.meta.outputs.version }}

      - name: Helm Push
        run: |
          helm push charts/stpm-${{ steps.helm-version.outputs.version }}.tgz oci://ghcr.io/clarkperkins
