name: Deploy

on:
  push:
    tags: [ '*' ]
    branches: [ main ]

jobs:
  docker:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      image-version: ${{ steps.meta.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Build Dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          python -m pip install --upgrade poetry

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: clarkperkins
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/clarkperkins/stpm
          tags: |
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr
          flavor: |
            latest=${{ github.ref_name == github.event.repository.default_branch }}

      - name: Library Version
        id: version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "::set-output name=version::${{ steps.meta.outputs.version }}"
          else
            # Use the date as the semver instead
            echo "::set-output name=version::$(date +'%Y.%-m.%-d')-dev+${{ github.sha }}"
          fi

      - name: Set Library Version
        run: |
          poetry version ${{ steps.version.outputs.version }}

      - name: Docker Build and Push
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  helm:
    name: Helm Build & Push
    needs: docker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v3

      - name: Helm Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u clarkperkins --password-stdin https://ghcr.io

      - name: Helm Build
        run: |
          helm package charts/smartthings-metrics -u -d charts --version ${{ needs.docker.outputs.version }} --app-version ${{ needs.docker.outputs.image-version }}

      - name: Helm Push
        run: |
          helm push charts/smartthings-metrics-${{ needs.docker.outputs.version }}.tgz oci://ghcr.io/clarkperkins
