name: Deploy

on:
  push:
    tags: [ '*' ]
    branches: [ main ]

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    secrets:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  docker:
    name: Docker Build & Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: clarkperkins
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build and Push
        id: docker-build
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            APP_VERSION=${{ needs.build.outputs.version }}
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ needs.build.outputs.image-tags }}
          labels: ${{ needs.build.outputs.image-labels }}
          cache-from: type=registry,ref=ghcr.io/clarkperkins/shm:buildcache
          cache-to: type=registry,ref=ghcr.io/clarkperkins/shm:buildcache,mode=max

  helm:
    name: Helm Build & Push
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Login to GHCR
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | helm registry login -u clarkperkins --password-stdin https://ghcr.io

      - name: Helm Build
        run: |
          helm package charts/smart-home-metrics -u -d charts --version ${{ needs.build.outputs.version }} --app-version ${{ needs.build.outputs.image-version }}

      - name: Helm Push
        run: |
          helm push charts/smart-home-metrics-${{ needs.build.outputs.version }}.tgz oci://ghcr.io/clarkperkins
