name: Deploy

on:
  push:
    tags: [ '*' ]
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Publish Test Results in build.yml creates a check run
      checks: write
      # Docker jobs in build.yml push to GHCR
      packages: write

  helm:
    name: Helm Build & Push
    needs: build
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: clarkperkins
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Helm Build
        run: |
          helm package charts/smart-home-metrics -u -d charts --version ${{ needs.build.outputs.version }} --app-version ${{ needs.build.outputs.image-version }}

      - name: Helm Push
        run: |
          helm push charts/smart-home-metrics-${{ needs.build.outputs.version }}.tgz oci://ghcr.io/clarkperkins
