name: Pull Requests

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      # Publish Test Results in build.yml creates a check run
      checks: write
